assets:
  js_prod:
    - bundles/itkhorizontemplate/assets/build/itkhorizontemplate.min.js

modules:
  toolsModule:
    files:
      - bundles/itkhorizontemplate/apps/toolsModule/horizon-editor.js

apps:
